"""empty message

Revision ID: 0139c10bc1ed
Revises: b9734ae209c1
Create Date: 2022-05-31 16:44:46.152064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0139c10bc1ed'
down_revision = 'b9734ae209c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('subject', sa.String(length=200), nullable=False))
    op.drop_column('question', 'username')
    op.drop_column('user', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.VARCHAR(length=120), nullable=False))
    op.add_column('question', sa.Column('username', sa.VARCHAR(length=150), nullable=False))
    op.drop_column('question', 'subject')
    # ### end Alembic commands ###
