"""empty message

Revision ID: 2b6580434eb3
Revises: 4cbe4fa02976
Create Date: 2022-06-10 20:56:18.443313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b6580434eb3'
down_revision = '4cbe4fa02976'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dessert')
    op.drop_table('drink')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drink',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('decription', sa.TEXT(), nullable=False),
    sa.Column('one_serving_kca', sa.NUMERIC(), nullable=False),
    sa.Column('sodium_mg', sa.NUMERIC(), nullable=False),
    sa.Column('saturated_fat_g', sa.NUMERIC(), nullable=False),
    sa.Column('sugars_g', sa.NUMERIC(), nullable=False),
    sa.Column('protien_g', sa.NUMERIC(), nullable=False),
    sa.Column('caffeine', sa.NUMERIC(), nullable=False),
    sa.Column('size_name', sa.TEXT(), nullable=False),
    sa.Column('size_ml', sa.TEXT(), nullable=False),
    sa.Column('size_fluid_ounce', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dessert',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('decription', sa.TEXT(), nullable=False),
    sa.Column('one_serving_kca', sa.NUMERIC(), nullable=False),
    sa.Column('sodium_mg', sa.NUMERIC(), nullable=False),
    sa.Column('saturated_fat_g', sa.NUMERIC(), nullable=False),
    sa.Column('sugars_g', sa.NUMERIC(), nullable=False),
    sa.Column('protien_g', sa.NUMERIC(), nullable=False),
    sa.Column('caffeine', sa.NUMERIC(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
