"""empty message

Revision ID: 3d2d2b00bfef
Revises: 7cb3aa6b2b23
Create Date: 2022-05-25 13:10:11.289848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d2d2b00bfef'
down_revision = '7cb3aa6b2b23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dessert',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('decription', sa.Text(), nullable=False),
    sa.Column('one_serving_kca', sa.Numeric(), nullable=False),
    sa.Column('sodium_mg', sa.Numeric(), nullable=False),
    sa.Column('saturated_fat_g', sa.Numeric(), nullable=False),
    sa.Column('sugars_g', sa.Numeric(), nullable=False),
    sa.Column('protien_g', sa.Numeric(), nullable=False),
    sa.Column('caffeine', sa.Numeric(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dessert')
    # ### end Alembic commands ###
