"""empty message

Revision ID: 7cb3aa6b2b23
Revises: 4ca1f3318850
Create Date: 2022-05-25 13:08:35.806510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cb3aa6b2b23'
down_revision = '4ca1f3318850'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drink', sa.Column('decription', sa.Text(), nullable=False))
    op.add_column('drink', sa.Column('one_serving_kca', sa.Numeric(), nullable=False))
    op.add_column('drink', sa.Column('sodium_mg', sa.Numeric(), nullable=False))
    op.add_column('drink', sa.Column('saturated_fat_g', sa.Numeric(), nullable=False))
    op.add_column('drink', sa.Column('sugars_g', sa.Numeric(), nullable=False))
    op.add_column('drink', sa.Column('protien_g', sa.Numeric(), nullable=False))
    op.add_column('drink', sa.Column('caffeine', sa.Numeric(), nullable=False))
    op.add_column('drink', sa.Column('size_name', sa.Text(), nullable=False))
    op.add_column('drink', sa.Column('size_ml', sa.Text(), nullable=False))
    op.add_column('drink', sa.Column('size_fluid_ounce', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drink', 'size_fluid_ounce')
    op.drop_column('drink', 'size_ml')
    op.drop_column('drink', 'size_name')
    op.drop_column('drink', 'caffeine')
    op.drop_column('drink', 'protien_g')
    op.drop_column('drink', 'sugars_g')
    op.drop_column('drink', 'saturated_fat_g')
    op.drop_column('drink', 'sodium_mg')
    op.drop_column('drink', 'one_serving_kca')
    op.drop_column('drink', 'decription')
    # ### end Alembic commands ###
