"""empty message

Revision ID: d5f999cae523
Revises: 0139c10bc1ed
Create Date: 2022-05-31 17:16:19.413035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5f999cae523'
down_revision = '0139c10bc1ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dessert',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('decription', sa.Text(), nullable=False),
    sa.Column('one_serving_kca', sa.Numeric(), nullable=False),
    sa.Column('sodium_mg', sa.Numeric(), nullable=False),
    sa.Column('saturated_fat_g', sa.Numeric(), nullable=False),
    sa.Column('sugars_g', sa.Numeric(), nullable=False),
    sa.Column('protien_g', sa.Numeric(), nullable=False),
    sa.Column('caffeine', sa.Numeric(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drink',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('decription', sa.Text(), nullable=False),
    sa.Column('one_serving_kca', sa.Numeric(), nullable=False),
    sa.Column('sodium_mg', sa.Numeric(), nullable=False),
    sa.Column('saturated_fat_g', sa.Numeric(), nullable=False),
    sa.Column('sugars_g', sa.Numeric(), nullable=False),
    sa.Column('protien_g', sa.Numeric(), nullable=False),
    sa.Column('caffeine', sa.Numeric(), nullable=False),
    sa.Column('size_name', sa.Text(), nullable=False),
    sa.Column('size_ml', sa.Text(), nullable=False),
    sa.Column('size_fluid_ounce', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('answer')
    op.drop_table('user')
    op.drop_table('question')
    op.drop_table('drink')
    op.drop_table('dessert')
    # ### end Alembic commands ###
