"""empty message

Revision ID: e54bbee8ce90
Revises: 97348fb71b43
Create Date: 2022-06-05 20:12:23.799417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e54bbee8ce90'
down_revision = '97348fb71b43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('fk_answer_user_id_user'), 'answer', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('answer', 'modify_date')
    op.create_foreign_key(op.f('fk_question_user_id_user'), 'question', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('uq_user_email'), 'user', ['email'])
    op.create_unique_constraint(op.f('uq_user_username'), 'user', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_user_username'), 'user', type_='unique')
    op.drop_constraint(op.f('uq_user_email'), 'user', type_='unique')
    op.drop_constraint(op.f('fk_question_user_id_user'), 'question', type_='foreignkey')
    op.add_column('answer', sa.Column('modify_date', sa.DATETIME(), nullable=True))
    op.drop_constraint(op.f('fk_answer_user_id_user'), 'answer', type_='foreignkey')
    # ### end Alembic commands ###
